# Generated by Django 5.2.10 on 2026-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('biryani', 'Biryani'), ('pizza', 'Pizza'), ('burger', 'Burger'), ('south', 'South Indian'), ('north', 'North Indian'), ('chinese', 'Chinese'), ('dessert', 'Dessert')], default='biryani', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
